Created HTML structure for site pages
INF6420/ss22-CBreul pull request #3
Opened 2022-05-31 00:26 UTC by CBreul

Added HTML skeletons for Index, The Party, NPCs and Monsters, and the Battle Log.

2022-05-31 17:32 UTC, axamei requested changes
Hi @CBreul it looks like you are missing an HTML file for locations.

2022-05-31 17:32 UTC, axamei commented on index.html
> +            <img src="images/TempLogo.jpg" style="float:left;" height="80" width="80" alt="An image of three red first-edition Dungeons and Dragons manuals on a white tablecloth, next to a blue bag o
Let's wait for the CSS section to handle styling.

2022-05-31 21:41 UTC, CBreul commented on index.html
> +            <img src="images/TempLogo.jpg" style="float:left;" height="80" width="80" alt="An image of three red first-edition Dungeons and Dragons manuals on a white tablecloth, next to a blue bag o
Hi Professor Liauw! Apologies - Locations was a page I thought I wanted but ended up not needing, and I forgot to remove it from the nav. I have removed references to Locations, as well as the styling from the header image.

2022-06-02 12:51 UTC, axamei approved these changes
👍

2022-06-02 12:51 UTC, merged